stages:
   - build

docker-build:
   image: carlonluca/docker-multiarch:dev-groovy
   stage: build
   services:
      - docker:dind
   before_script:
      - docker login -u "$CI_DOCKER_HUB_USER" -p "$CI_DOCKER_HUB_PASSWORD" docker.io
   script:
      - export DOCKER_CLI_EXPERIMENTAL=enabled
      - docker run --privileged --rm tonistiigi/binfmt --install all
      - docker buildx create --name multiarch_builder --use --platform linux/arm64/v8,linux/386,linux/arm/v7,linux/arm/v6,linux/amd64,linux/386
      - docker buildx build --push --platform linux/arm64/v8,linux/amd64 -t carlonluca/docker-multiarch:$VERSION-groovy -f Dockerfile_groovy .
      - docker buildx build --push --platform linux/arm64/v8,linux/386,linux/arm/v7,linux/arm/v6,linux/amd64,linux/386 -t carlonluca/docker-multiarch:$VERSION -f Dockerfile .
      - docker stop multiarch_builder
      - docker rm multiarch_builder
   rules:
      - when: manual
